language: node_js

before_install:
  - npm install --global istanbul codeclimate-test-reporter

script:
  - istanbul cover -x '**/vendor/**' node_modules/mocha/bin/_mocha

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
